Get credentials from the internal api instead of secrets manager
solid-adventure/trivial-core pull request #7
Opened 2023-07-11 16:07 UTC by david-richards-tech

What does this PR do?
Get credentials from the internal api instead of secrets manager if APP_API_KEY exists in the environment. This is part of the work to move credentials from secrets manager AWS to internal encrypted table.

2023-07-13 20:42 UTC, vgkids requested changes
Looks workable overall, just looking for clarity on naming.

2023-07-13 20:42 UTC, vgkids commented on lib/AppBuilder.js
> +    await this._ensureCorrectLayers(client, info, layers, manifest)
Why is `manifest` now being passed here, I don't see that we changed the method?

2023-07-13 20:42 UTC, vgkids commented on lib/AppBuilder.js
> +    await this._updateEnvironment(client, manifest)
This likes it will fix https://github.com/solid-adventure/trivial-core/issues/2, is that right?

2023-07-13 20:42 UTC, vgkids commented on lib/CredentialManager.js
> +    if (process.env.APP_API_KEY) {
The name of the env var and the behavior are out of sync; I wouldn't expect the presence of `APP_API_KEY` to change where my credentials are being fetched from.

How about `process.env.CREDENTIALS_SERVICE`?

So your conditional might be `if (process.env.CREDENTIALS_SERVICE == 'TRIVIAL-API' && process.env.TRIVIAL_API_KEY) {...`

Then we'd set the default CREDENTIALS_SERVICE to 'TRIVIAL-API' on all new apps, and older apps will continue to pick up the AWS / unset version until we migrate them.

2023-07-13 20:42 UTC, vgkids commented on lib/CredentialManager.js
>      const response = await awsFetch('/', {
We'd only do this AWS fetch if the CREDENTIALS_SERVICE was set to `AWS_SECRETS_MANAGER` or blank.

2023-07-14 13:50 UTC, david-richards-tech commented on lib/AppBuilder.js
> +    await this._ensureCorrectLayers(client, info, layers, manifest)
This was left by mistake. I was going to make the update all in one section with the layers, but changed my mind.

2023-07-14 13:50 UTC, david-richards-tech commented on lib/AppBuilder.js
> +    await this._updateEnvironment(client, manifest)
Yes

2023-07-14 14:20 UTC, david-richards-tech commented on lib/CredentialManager.js
> +    if (process.env.APP_API_KEY) {
Resolved

2023-07-31 15:52 UTC, vgkids commented on lib/CredentialManager.js
> +            'authorization': `Bearer ${process.env.APP_API_KEY}`
We use `TRIVIAL_API_KEY` on 109, and `APP_API_KEY` here, so this 401's 100% of the time. It also highlights the need for an easier way to exercise this– let's get tests on this including the 401, 404, 200, and token expired/refresh paths.

2023-07-31 16:34 UTC, david-richards-tech commented on lib/CredentialManager.js
> +            'authorization': `Bearer ${process.env.APP_API_KEY}`
This env variable has been resolved.

2023-08-03 18:38 UTC, vgkids requested changes
CredentialManager needs tests before this can be merged.

2023-08-03 18:38 UTC, vgkids commented on lib/CredentialManager.js
> +          'authorization': `Bearer ${process.env.APP_API_KEY}`
This is the same misnamed API key var we saw before, right?

Please add tests that exercise these methods.

2023-08-29 00:20 UTC, vgkids commented
trivial-hosted secret store concept rolled back.

2023-08-29 00:20 UTC, closed without merging